version: 0.1.1

default:
  # PostgreSQL connection
  POSTGRES_CONNECT_TIMEOUT: 10
  POSTGRES_DBNAME: "{{ env_var('POSTGRES_DB') }}"
  POSTGRES_HOST: "{{ env_var('POSTGRES_HOST') }}"
  POSTGRES_PASSWORD: "{{ env_var('POSTGRES_PASSWORD') }}"
  POSTGRES_PORT: "{{ env_var('POSTGRES_PORT') }}"
  POSTGRES_USER: "{{ env_var('POSTGRES_USER') }}"
